// Generador de nombres para bots

const BOT_NAMES = [
  "El Rompecurvas",
  "Agent Potato",
  "Soy Mejor Que Tú",
  "WiFi Disconnected",
  "La Abuela Veloz",
  "Ctrl+Alt+Defeat",
  "Pato Lógico",
  "lag_monster",
  "No Era Mi Intención",
  "Random Person 42",
  "Tu Peor Pesadilla",
  "Why So Serious?",
  "El Bot Malo",
  "Spamming_Curves",
  "El Último y Nos Vamos",
  "Just a Glitch",
  "Doctor Desastre",
  "AFK_Master",
  "El Manco Legendario",
  "Error 404: Skill Not Found",
  "Capitán Obvio",
  "Totally Not a Bot",
  "El Que Se Estampa",
  "The Annoying One",
  "Un Tal Manolo",
  "Missed Shot",
  "Dame Más Puntos",
  "The Curve Whisperer",
  "El Gato con Casco",
  "Powered by Caffeine",
  "¡Qué Risa!",
  "Bad Decisions Only",
  "El Bot Inesperado",
  "Do Not Follow",
  "El Amigo Imaginario",
  "Procrastinator",
  "El Que Va Lento",
  "The Plot Twist",
  "Soy Una Máquina (de Churros)",
  "Unskilled & Unaware",
  "El Pez Payaso",
  "Need More Boost",
  "El Amo del Lag",
  "Call an Ambulance",
  "El Que Pasaba Por Ahí",
  "My Other Ride is a Curve",
  "El Turbo de la Abuela",
  "Wait For Me!",
  "El Ídolo de las Curvas",
  "The Real MVP (Most Valuable Potato)",
];

export function generateBotName(): string {
  const name = BOT_NAMES[Math.floor(Math.random() * BOT_NAMES.length)];
  return name;
}
